--
-- PostgreSQL database dump
--

-- Dumped from database version 10.22 (Ubuntu 10.22-0ubuntu0.18.04.1)
-- Dumped by pg_dump version 10.22 (Ubuntu 10.22-0ubuntu0.18.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: sc_authority; Type: TABLE; Schema: public; Owner: sc_usr
--

CREATE TABLE IF NOT EXISTS public.sc_authority (
    name character varying(50) NOT NULL
);


ALTER TABLE public.sc_authority OWNER TO sc_usr;

--
-- Name: sc_job; Type: TABLE; Schema: public; Owner: sc_usr
--

CREATE TABLE IF NOT EXISTS public.sc_job (
    id bigint NOT NULL,
    create_time timestamp without time zone,
    operation_system character varying(255),
    browser character varying(255),
    status character varying(255),
    status_description character varying(255),
    url character varying(255),
    uuid character varying(255),
    task_id bigint
);


ALTER TABLE public.sc_job OWNER TO sc_usr;

--
-- Name: sc_job_id_seq; Type: SEQUENCE; Schema: public; Owner: sc_usr
--

ALTER TABLE public.sc_job ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sc_job_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sc_task; Type: TABLE; Schema: public; Owner: sc_usr
--

CREATE TABLE IF NOT EXISTS public.sc_task (
    id bigint NOT NULL,
    create_time timestamp without time zone,
    iosipad boolean,
    iosiphone_pro boolean,
    iosiphone_se boolean,
    lin_chrome boolean,
    lin_firefox boolean,
    lin_opera boolean,
    resolution character varying(255),
    url character varying(255) NOT NULL,
    uuid character varying(255),
    win_chrome boolean,
    win_edge boolean,
    win_firefox boolean,
    win_opera boolean,
    user_id bigint,
    mac_safari boolean,
    mac_firefox boolean,
    mac_chrome boolean
);


ALTER TABLE public.sc_task OWNER TO sc_usr;

--
-- Name: sc_task_id_seq; Type: SEQUENCE; Schema: public; Owner: sc_usr
--

ALTER TABLE public.sc_task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sc_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sc_user; Type: TABLE; Schema: public; Owner: sc_usr
--

CREATE TABLE IF NOT EXISTS public.sc_user (
    id bigint NOT NULL,
    email character varying(255),
    name character varying(255),
    password_hash character varying(255),
    enabled boolean
);


ALTER TABLE public.sc_user OWNER TO sc_usr;

--
-- Name: sc_user_id_seq; Type: SEQUENCE; Schema: public; Owner: sc_usr
--

ALTER TABLE public.sc_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sc_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token; Type: TABLE; Schema: public; Owner: sc_usr
--

CREATE TABLE IF NOT EXISTS public.token (
    id bigint NOT NULL,
    createtime timestamp without time zone,
    uuid character varying(255),
    user_id bigint
);


ALTER TABLE public.token OWNER TO sc_usr;

--
-- Name: token_id_seq; Type: SEQUENCE; Schema: public; Owner: sc_usr
--

ALTER TABLE public.token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sc_authority sc_authority_pkey; Type: CONSTRAINT; Schema: public; Owner: sc_usr
--

ALTER TABLE ONLY public.sc_authority
    ADD CONSTRAINT sc_authority_pkey PRIMARY KEY (name);


--
-- Name: sc_job sc_job_pkey; Type: CONSTRAINT; Schema: public; Owner: sc_usr
--

ALTER TABLE ONLY public.sc_job
    ADD CONSTRAINT sc_job_pkey PRIMARY KEY (id);


--
-- Name: sc_task sc_task_pkey; Type: CONSTRAINT; Schema: public; Owner: sc_usr
--

ALTER TABLE ONLY public.sc_task
    ADD CONSTRAINT sc_task_pkey PRIMARY KEY (id);


--
-- Name: sc_user sc_user_pkey; Type: CONSTRAINT; Schema: public; Owner: sc_usr
--

ALTER TABLE ONLY public.sc_user
    ADD CONSTRAINT sc_user_pkey PRIMARY KEY (id);


--
-- Name: token token_pkey; Type: CONSTRAINT; Schema: public; Owner: sc_usr
--

ALTER TABLE ONLY public.token
    ADD CONSTRAINT token_pkey PRIMARY KEY (id);


--
-- Name: idx8xhcloflal55874pkuqocbajp; Type: INDEX; Schema: public; Owner: sc_usr
--

CREATE INDEX idx8xhcloflal55874pkuqocbajp ON public.sc_task USING btree (uuid);


--
-- Name: idxeo0882tc4lk8gvpv6fy9ry7tl; Type: INDEX; Schema: public; Owner: sc_usr
--

CREATE INDEX idxeo0882tc4lk8gvpv6fy9ry7tl ON public.sc_job USING btree (uuid);


--
-- Name: sc_job fk1f8ac960wuxaxlwr9ja9ydyy9; Type: FK CONSTRAINT; Schema: public; Owner: sc_usr
--

ALTER TABLE ONLY public.sc_job
    ADD CONSTRAINT fk1f8ac960wuxaxlwr9ja9ydyy9 FOREIGN KEY (task_id) REFERENCES public.sc_task(id);


--
-- Name: sc_task fkiihg9x7mamik6j4cg3jc8qxt0; Type: FK CONSTRAINT; Schema: public; Owner: sc_usr
--

ALTER TABLE ONLY public.sc_task
    ADD CONSTRAINT fkiihg9x7mamik6j4cg3jc8qxt0 FOREIGN KEY (user_id) REFERENCES public.sc_user(id);


--
-- Name: token fkk7qmnognjrf06mqcy0iyslgfa; Type: FK CONSTRAINT; Schema: public; Owner: sc_usr
--

ALTER TABLE ONLY public.token
    ADD CONSTRAINT fkk7qmnognjrf06mqcy0iyslgfa FOREIGN KEY (user_id) REFERENCES public.sc_user(id);

